/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

fun holaA() {
    println("Agustín, 25/4/25")
}

fun arear(base: Double, altura: Double): Double {
    return base * altura
}

fun pnc(numero: Int): String {
    return when {
        numero > 0 -> "positivo"
        numero < 0 -> "negativo"
        else -> "cero"
    }
}

fun pv(){
    for (i in 0..20){
        if (i % 2 == 0){
            println(i)
        }
    }
}

fun potencia(){
    
}

fun maxmin(){
    val notas = listOf(8, 7, 9, 10, 5) 
    val Max = notas.max()
    val Min = notas.min()
    println("Máximo: $Max")
    println("Mínimo: $Min")
}

fun main() {
    holaA()
    println(arear(1.5,1.0))
    println(pnc(-3)) 
    pv()
    maxmin()
}
