/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

class App {
    val greeting: String
        get() {
            return "Hello World!"
        }
}
fun holaK(){
    println("Hola, Kotlin")
}
fun Datos() {
    val nombre: String = "Agustín"
    val edad: Int = 16
    val altura: Double = 1.75
    val esEstudiante: Boolean = true
    
    println("Nombre: $nombre")
    println("Edad: $edad")
    println("Altura: $altura")
    println("Es estudiante: $esEstudiante")
}
fun main() {
    println(holaK())
    println(Datos())
}
